<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RootElement" nsURI="http:///RootElement.ecore" nsPrefix="RootElement">
  <eSubpackages name="DefaultCollaborationDiagram" nsURI="http:///RootElement/DefaultCollaborationDiagram.ecore"
      nsPrefix="RootElement.DefaultCollaborationDiagram">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Default Collaboration Diagram"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="CompradeRefrigerante" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Balconista" eSuperTypes="#//DefaultCollaborationDiagram/CompradeRefrigerante #//DefaultCollaborationDiagram/RefrigeranteIndisponivel_Service #//DefaultCollaborationDiagram/RefrigeranteIndisponivel_Request #//DefaultCollaborationDiagram/Fim_Service #//DefaultCollaborationDiagram/Fim_Request #//DefaultCollaborationDiagram/VerificarDisponibilidade_Request #//DefaultCollaborationDiagram/VerificarDinheiroDisponivel_Service #//DefaultCollaborationDiagram/RefrigeranteDisponivel_Service #//DefaultCollaborationDiagram/RefrigeranteDisponivel_Request #//DefaultCollaborationDiagram/EntregarRefrigerante_Request">
      <eOperations name="EntregarRefrigerante" ordered="false" lowerBound="1"/>
      <eOperations name="VerificarDisponibilidade" ordered="false" lowerBound="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RefrigeranteIndisponivel_Service"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="RefrigeranteIndisponivel_Request"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fim_Service" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fim_Request" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="VerificarDisponibilidade_Request"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="VerificarDinheiroDisponivel_Service"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="RefrigeranteDisponivel_Service" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="RefrigeranteDisponivel?_Service"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RefrigeranteDisponivel_Request" abstract="true"
        interface="true">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="RefrigeranteDisponivel?_Request"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntregarRefrigerante_Request" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cliente" eSuperTypes="#//DefaultCollaborationDiagram/CompradeRefrigerante #//DefaultCollaborationDiagram/VerificarDisponibilidade_Service #//DefaultCollaborationDiagram/SolicitarRefrigerante_Service #//DefaultCollaborationDiagram/SolicitarRefrigerante_Request #//DefaultCollaborationDiagram/VerificarDinheiroDisponivel_Request #//DefaultCollaborationDiagram/Pagamentonaorealizado_Service #//DefaultCollaborationDiagram/Pagamentonaorealizado_Request #//DefaultCollaborationDiagram/PossuiDinheiroSuficiente_Service #//DefaultCollaborationDiagram/PossuiDinheiroSuficiente_Request #//DefaultCollaborationDiagram/EntregarRefrigerante_Service #//DefaultCollaborationDiagram/RealizarPagamento_Service #//DefaultCollaborationDiagram/RealizarPagamento_Request">
      <eOperations name="RealizarPagamento" ordered="false" lowerBound="1"/>
      <eOperations name="SolicitarRefrigerante" ordered="false" lowerBound="1"/>
      <eOperations name="VerificarDinheiroDisponivel" ordered="false" lowerBound="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VerificarDisponibilidade_Service"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SolicitarRefrigerante_Service" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SolicitarRefrigerante_Request" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="VerificarDinheiroDisponivel_Request"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pagamentonaorealizado_Service" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pagamentonaorealizado_Request" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PossuiDinheiroSuficiente_Service"
        abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="PossuiDinheiroSuficiente?_Service"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PossuiDinheiroSuficiente_Request"
        abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="PossuiDinheiroSuficiente?_Request"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntregarRefrigerante_Service" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealizarPagamento_Service" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealizarPagamento_Request" abstract="true"
        interface="true"/>
  </eSubpackages>
</ecore:EPackage>
